### ISSUE TITLE
Noto Serif Dives Akuru Ligating issue

### ISSUE THREAD

**Issue by Ismailizyanilyas** [notofonts/dives-akuru#16]
### Font 
  >   NotoSerifDivesAkuru-Regular.ttf
[https://github.com/notofonts/noto-fonts/blob/main/unhinted/ttf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.ttf]
  >   Site: https://github.com/notofonts/noto-fonts/blob/main/unhinted/ttf/NotoSerifDivesAkuru/NotoSerifDivesAkuru-Regular.ttf
  >   Date: 2022-08-06

### Font Version
1.000

### Application name and version
  > Microsoft Word version 2201

### Issue

  1. Steps to reproduce: Copy and paste U+1190C (letter ka), U+1193E (The ligature maker) and U+1192B (letter ssa) from a site with the characters (because there is no keyboard for Dives Akuru block)(example site: https://unicode-table.com/en/blocks/dives-akuru/) into Microsoft Word.
  2. The characters did not ligate and they changed into other fonts (Tahoma and Calibri) which do not support the characters, and other issues occurred to the rest of the text in the document, such as them changing into other fonts.
  3. The characters were expected to ligate into this ligature, as written in the proposal to encode Dives Akuru:
![image](https://user-images.githubusercontent.com/109751263/183286012-66f38549-c3d6-4e96-8ff9-54f380e4dd09.png)
  4. Additional information: This issue occurs in all the other characters as well.

### Character data
  > Dives Akuru 11900—1195F
1190C 𑤌 DIVES AKURU LETTER KA
1192B 𑤫 DIVES AKURU LETTER SSA
1193E 𑤾 DIVES AKURU VIRAMA

𑤌 𑤾𑤫 <The issue

### Screenshot of issue
![image](https://user-images.githubusercontent.com/109751263/183286297-b2f02888-5530-454e-982e-4aec1d6717cc.png)

when I click the end of the last glyph, this happens:
![image](https://user-images.githubusercontent.com/109751263/183286193-f90413b5-e851-4a60-8e7d-eb00023fc1cd.png)

**Comment by simoncozens** [comment]
The Dives Akuru font does have a KSSA ligature. In the sample text you pasted above, there is a space between the KA and the VIRAMA. This is blocking the ligature. If you remove that space, it works fine; please try pasting this text: 𑤌𑤾𑤫.

**Comment by Ismailizyanilyas** [comment]
There is a space in between the letters. That was my issue.
However, I pasted that text and still got the same results:
![image](https://user-images.githubusercontent.com/109751263/185141901-a16e70db-7f6d-4800-a088-cc85f2c61bd6.png)
Maybe it might be an issue with Word supporting the font.

**Comment by simoncozens** [comment]
I think it probably is a Windows issue; it seems not to be applying the cjct feature. What version of Windows is this?

**Comment by Ismailizyanilyas** [comment]
Version 1903

**Comment by Ismailizyanilyas** [comment]
The diacritics' ligatures and medial ya are also not supported:
![image](https://user-images.githubusercontent.com/109751263/186889811-c6fd1015-3b38-44c8-b8e2-b478425b0402.png)

**Comment by simoncozens** [comment]
That was rolled out before Dives Akuru was added to Unicode, so I suspect it will not know what to do with Dives Akuru fonts. I presume an update will fix it, but if not, let's report to Microsoft.
